"""add tool detail fields

Revision ID: eae7f52c79f1
Revises: 4b9247a9cff4
Create Date: 2026-03-04 15:19:37.494740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae7f52c79f1'
down_revision = '4b9247a9cff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('pricing', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('developer', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('developer')
        batch_op.drop_column('platform')
        batch_op.drop_column('pricing')
        batch_op.drop_column('tags')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('description_html')

    # ### end Alembic commands ###
